use SalesProject

CREATE TABLE ITEMTYPE_DIMENTION (
	ID INT PRIMARY KEY NOT NULL,
	ITEMNAME VARCHAR(50) NOT NULL,
	UNITPRICE FLOAT NOT NULL,
	UNITCOST FLOAT NOT NULL
);
select * from ITEMTYPE_DIMENTION;

drop table LOCATION_DIMENTION;
CREATE TABLE LOCATION_DIMENTION (
	LOCATIONID INT PRIMARY KEY NOT NULL,
	CONTINENT VARCHAR(100) NOT NULL,
	COUNTRY VARCHAR(100) NOT NULL	
);
select * from LOCATION_DIMENTION;
drop table 
CREATE TABLE DATE_TIME_DIM(
	DATEID INT PRIMARY KEY ,
	DAYOFWEEK_ INT NOT NULL,
	DAYOFYEAR_ INT NOT NULL,
	MONTH_ INT NOT NULL,
	YEAR_ INT NOT NULL,
	DATE_ VARCHAR(50) NOT NULL
);

select * from DATE_TIME_DIM;

CREATE TABLE ORDER_DIM(
	ORDERID INT PRIMARY KEY ,
	ORDERPRIORITY VARCHAR(10) NOT NULL,
	SALESCHANNEL VARCHAR(10) NOT NULL,
);
select * from ORDER_DIM where ORDERID=97;
drop table ORDER_DIM;
delete  from ORDER_DIM;

CREATE TABLE SALES_FACT_TABLE (
	LOCATIONID INT FOREIGN KEY REFERENCES LOCATION_DIMENTION(LOCATIONID),
	ITEMTYPEID INT FOREIGN KEY REFERENCES ITEMTYPE_DIMENTION(ID),
	ORDERID INT FOREIGN KEY REFERENCES ORDER_DIM(ORDERID),
	DATEID INT FOREIGN KEY REFERENCES DATE_TIME_DIM(DATEID),
	TOTALREVENUE FLOAT NOT NULL,
	TOTALCOST FLOAT NOT NULL,
	TOTALPROFIT FLOAT ,
	UNITSOLD FLOAT NOT NULL
);

select * from SALES_FACT_TABLE;

drop table SALES_FACT_TABLE;